Update home/.bashrc

diff --git a/home/dot_bashrc b/home/dot_bashrc
--- a/home/dot_bashrc
+++ b/home/dot_bashrc
@@ -27,9 +27,16 @@ pathmunge () {
     esac
 }
 
-get-github-latest () {
-    git ls-remote --tags --sort=v:refname $1 | grep -v "rc" | grep -v "{}"  | grep -v "release" | tail -n 1 | tr -d '[:space:]' |  rev | cut -d/ -f1 | rev
-}
+GFILE="$HOME/scripts/github-latest.fn"
+if [[ -f $GFILE ]]; then
+    . "$GFILE"
+else
+    echo "$GFILE is missing."
+    #exit 1
+fi
+#get-github-latest () {
+#    git ls-remote --tags --sort=v:refname $1 | grep -v "rc" | grep -v "{}"  | grep -v "release" | tail -n 1 | tr -d '[:space:]' |  rev | cut -d/ -f1 | rev
+#}
 
 # don't put duplicate lines or lines starting with space in the history.
 # See bash(1) for more options
